name: Run Application

on:
  # Allow this workflow to be called by other workflows
  workflow_call: {}

  # Allow this workflow to be triggered manually
  workflow_dispatch: {}

jobs:
  run-application:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "22" # Replace with your preferred Node.js version

      # Step 3: Install Node.js dependencies
      - name: Install dependencies
        run: npm install

      # Step 4: Run your Node.js application
      - name: Run application
        # Pass the secrets in as an environment variables
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          GOOGLEAI_API_KEY: ${{ secrets.GOOGLEAI_API_KEY }}
          EMAIL: ${{ secrets.EMAIL }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
        run: npm start

      # Step 5: Configure Git User (required to commit changes to the repository)
      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      # Step 6: Commit the changes to Persist the AI Chat History
      - name: Commit changes
        run: |
          git add history.json
          git commit -m "update chat history (automated)"
          git push
