name: Timezone

on:
  workflow_call:
    inputs:
      timezone:
        required: true
        type: string
      hour:
        required: true
        type: string
    outputs:
      result:
        value: ${{ jobs.check-timezone.outputs.result }}

jobs:
  check-timezone:
    runs-on: ubuntu-latest

    outputs:
      result: ${{ steps.check.outputs.result }}

    steps:
      # Step 1: Perform the Timezone check
      - name: Check Timezone
        id: check
        run: |
          current_hour=$(TZ='${{ inputs.timezone }}' date +'%H')
          echo "Given hour: ${{ inputs.hour }}"
          echo "Current hour: $current_hour (${{ inputs.timezone }})"
          
          if [ "$current_hour" == "${{ inputs.hour }}" ]; then
            echo "result=true" >> $GITHUB_OUTPUT
          else
            echo "result=false" >> $GITHUB_OUTPUT
          fi
